export default {
    // INTRO BASED 
    INTRO: "INTRO",
    INTRO_PRODUCT: "INTRO_PRODUCT",
    INTRO_PAYMENT: "INTRO_PAYMENT",
    INTRO_DELIVERY: "INTRO_DELIVERY",

    // Tab navigator
    BOTTOM_TAB_NAVIGATOR: "BOTTOM_TAB_NAVIGATOR",

    // HOME BASED
    HOME: "HOME",
    HOME_NAVIGATOR: "HOME_NAVIGATOR",
    ALL_CATEGORIES: "ALL_CATEGORIES",
    ALL_PRODUCTS: "ALL_PRODUCTS",
    PRODUCT: "PRODUCT",
    HOME_REVIEW: "HOME_REVIEW",
    CART: "CART",
    PAYMENT: "PAYMENT",
    SEARCH: "SEARCH",

    PRODUCT_DESCRIPTION: "PRODUCT_DESCRIPTION",
    PRODUCT_REVIEW: "PRODUCT_REVIEW",
    PRODUCT_INFO: "PRODUCT_INFO",
    
    
    // PROFILE BASED
    PROFILE: "PROFILE",
    PROFILE_SCREEN: "PROFILE_SCREEN",
    PROFILE_NOTIFICATION: "PROFILE_NOTIFICATION",
    EDIT_PAYMENT: "PAYMENT",
    EDIT_ADDRESS: "EDIT_ADDRESS",
    PAYPAL: "PAYPAL",
    GPAY: "GPAY",
    CARD: "CARD",
    
    // ORDER BASED
    ORDER: "ORDER",
    ORDER_DELIVERED: "ORDER_DELIVERED",
    ORDER_PROCESSING: "ORDER_PROCESSING",
    ORDER_CANCELED: "ORDER_CANCELED",
    ORDER_SUCCESS: "SUCCESS",
    ORDER_FAIL: "FAIL",

    // Login
    LOGIN: "LOGIN",

    // Sign
    SIGN_UP: "SIGN_UP"
}