export default {
    // INTRO BASED 
    INTRO: "INTRO",
    INTRO_PRODUCT: "INTRO_PRODUCT",
    INTRO_PAYMENT: "INTRO_PAYMENT",
    INTRO_DELIVERY: "INTRO_DELIVERY",

    // HOME BASED
    HOME: "HOME",
    ALL_CATEGORIES: "ALL_CATEGORIES",
    NEW_ARRIVAL: "NEW_ARRIVAL",
    BEST_SELLING: "BEST_SELLING",
    DISCOUNT_PRODUCTS: "DISCOUNT_PRODUCTS",
    HIGH_PRICE: "HIGH_PRICE",
    LOW_PRICE: "LOW_PRICE",
    FREE_DELIVERY: "FREE_DELIVERY",
    PRODUCT: "PRODUCT",
    REVIEW: "REVIEW",
    
    
    // PROFILE BASED
    PROFILE: "PROFILE",
    PAYMENT: "PAYMENT",
    EDIT_ADDRESS: "EDIT_ADDRESS",
    PAYPAL: "PAYPAL",
    GPAY: "GPAY",
    CARD: "CARD",
    
    // ORDER BASED
    ORDER: "ORDER",
    ORDER_DELIVERED: "ORDER_DELIVERED",
    ORDER_PROCESSING: "ORDER_PROCESSING",
    ORDER_CANCELED: "ORDER_CANCELED",
    ORDER_SUCCESS: "SUCCESS",
    ORDER_FAIL: "FAIL",
}